In [16]:
# %load classification_template.py
# Classification template

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

## Part 1: Data Pre-processing

In [17]:
#Selecting the independent and dependent variables based on which independent have impact in the dependent

X = dataset.iloc[:, 3:13].values #Independent variables 3 to 12 (note we wrote 13 because isn't included)
y = dataset.iloc[:, 13].values  #Dependant variable

In [18]:
# %load categorical_data.py
# Data Preprocessing

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [19]:
# This makes dummy variables, which fixes that when encoding categorical data, 2>0 and that tricks the neural network,
# and also any machine learning model.

# Because we have 3 different values in country, it creates 3 columns with the dummy variables.

onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [20]:
X = X[:,1:]
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [21]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [22]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2: Building the ANN

In [23]:
# Importing needed modules

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [24]:
# Initializing the ANN ( Building the Layers )

classifier = Sequential()

In [25]:
# Creating the Layers of our ANN

# Input Layer and First Hidden Layer WITH  OPTIONAL DROPOUT TO REDUCE OVERFITTING.

classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
# classifier.add(Dropout(rate = 0.1)) # First time try with 0.1. Never over 0.5.

In [26]:
# Second Hidden Layer

classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
# classifier.add(Dropout(rate = 0.1)) # First time try with 0.1. Never over 0.5.

In [27]:
# Output Layer

classifier.add(Dense(units = 1,kernel_initializer = 'uniform',activation = 'sigmoid'))

In [28]:
# Compiling the ANN

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [29]:
# Fitting the ANN to the Training set. TRAINING THE ANN.

classifier.fit(X_train, y_train, batch_size=10, epochs=25)

Epoch 1/25
8000/8000 [==============================] - 1s 105us/step - loss: 0.4856 - acc: 0.7957
Epoch 2/25
8000/8000 [==============================] - 1s 75us/step - loss: 0.4266 - acc: 0.7960
Epoch 3/25
8000/8000 [==============================] - 1s 75us/step - loss: 0.4198 - acc: 0.8146
Epoch 4/25
8000/8000 [==============================] - 1s 75us/step - loss: 0.4146 - acc: 0.8286
Epoch 5/25
8000/8000 [==============================] - 1s 75us/step - loss: 0.4105 - acc: 0.8322
Epoch 6/25
8000/8000 [==============================] - 1s 75us/step - loss: 0.4076 - acc: 0.8324
Epoch 7/25
8000/8000 [==============================] - 1s 75us/step - loss: 0.4061 - acc: 0.8324
Epoch 8/25
8000/8000 [==============================] - 1s 75us/step - loss: 0.4046 - acc: 0.8320
Epoch 9/25
8000/8000 [==============================] - 1s 75us/step - loss: 0.4033 - acc: 0.8316
Epoch 10/25
8000/8000 [==============================] - 1s 75us/step - loss: 0.4025 - acc: 0.8331
Epoch 11/25
8000/8

## Part 3: Making the Predictions and Evaluating the Model

In [30]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [31]:
y_pred = (y_pred > 0.5) # TRUE or FALSE for Classification Model.

In [32]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [33]:
cm

array([[1550,   45],
       [ 271,  134]])

In [39]:
Accuracy = (cm[0,0] + cm[1,1]) / (cm[0,0] + cm[0,1] + cm[1,0] + cm[1,1])

Accuracy

0.842

## Predicting if one customer will leave the bank

In [46]:
new_prediction = classifier.predict(sc.transform(np.array([[0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

In [45]:
new_prediction = (new_prediction > 0.5)
new_prediction

array([[False]])

## Part 4: Evaluating, Improving and Tuning the ANN

In [47]:
# Evaluating the ANN (K-Fold Cross Validation)

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [48]:
# Wrapping

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
    classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
    classifier.add(Dense(units = 1,kernel_initializer = 'uniform',activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    return classifier


classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 100)

accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10,
                             n_jobs = -1)#n_jobs = cpu cores used. -1 uses all.


In [49]:
mean = accuracies.mean()
variance = accuracies.std()
print(mean, variance)

0.7979999966174365 0.00995615343491111


In [50]:
# Tuning the ANN

import keras
from keras.models import Sequential
from keras.layers import Dense

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [51]:
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
    classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
    classifier.add(Dense(units = 1,kernel_initializer = 'uniform',activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    return classifier


classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
parameters = {'batch_size': [25,32], 
              'nb_epoch': [100,500],
             'optimizer': ['adam','rmsprop']}

grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', cv = 10)
grid_search = grid_search.fit(X_train, y_train)

best_parameters =  grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/1
7200/7200 [==============================] - 1s 72us/step - loss: 0.5566 - acc: 0.7967
Epoch 1/1
7200/7200 [==============================] - 1s 77us/step - loss: 0.5606 - acc: 0.7960
Epoch 1/1
7200/7200 [==============================] - 1s 82us/step - loss: 0.5687 - acc: 0.7937
Epoch 1/1
7200/7200 [==============================] - 1s 89us/step - loss: 0.5454 - acc: 0.7971
Epoch 1/1
7200/7200 [==============================] - 1s 91us/step - loss: 0.5615 - acc: 0.7926
Epoch 1/1
7200/7200 [==============================] - 1s 97us/step - loss: 0.5673 - acc: 0.7940
Epoch 1/1
7200/7200 [==============================] - 1s 101us/step - loss: 0.5584 - acc: 0.7960
Epoch 1/1
7200/7200 [==============================] - 1s 108us/step - loss: 0.5807 - acc: 0.7953
Epoch 1/1
7200/7200 [==============================] - 1s 115us/step - loss: 0.5757 - acc: 0.7946
Epoch 1/1
7200/7200 [==============================] - 1s 120us/step - loss: 0.5633 - acc: 0.7951
Epoch 1/1
7200/7200 [=====