In [1]:
# %load classification_template.py
# Classification template

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

## Part 1: Data Pre-processing

In [2]:
#Selecting the independent and dependent variables based on which independent have impact in the dependent

X = dataset.iloc[:, 3:13].values #Independent variables 3 to 12 (note we wrote 13 because isn't included)
y = dataset.iloc[:, 13].values  #Dependant variable

In [3]:
# %load categorical_data.py
# Data Preprocessing

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [4]:
# This makes dummy variables, which fixes that when encoding categorical data, 2>0 and that tricks the neural network,
# and also any machine learning model.

# Because we have 3 different values in country, it creates 3 columns with the dummy variables.

onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [5]:
X = X[:,1:]
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2: Building the ANN

In [8]:
# Importing needed modules

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

Using TensorFlow backend.


In [9]:
# Initializing the ANN ( Building the Layers )

classifier = Sequential()

W0920 20:21:11.867008 4504933824 deprecation_wrapper.py:119] From /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [10]:
# Creating the Layers of our ANN

# Input Layer and First Hidden Layer WITH DROPOUT TO REDUCE OVERFITTING.

classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
# classifier.add(Dropout(rate = 0.1)) # First time try with 0.1. Never over 0.5.

In [11]:
# Second Hidden Layer

classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
# classifier.add(Dropout(rate = 0.1)) # First time try with 0.1. Never over 0.5.

In [12]:
# Output Layer

classifier.add(Dense(units = 1,kernel_initializer = 'uniform',activation = 'sigmoid'))

In [13]:
# Compiling the ANN

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

W0920 20:21:11.907787 4504933824 deprecation_wrapper.py:119] From /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



In [14]:
# Fitting the ANN to the Training set. TRAINING THE ANN.

classifier.fit(X_train, y_train, batch_size=10, epochs=100)

W0920 20:21:11.933197 4504933824 deprecation_wrapper.py:119] From /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0920 20:21:11.937522 4504933824 deprecation_wrapper.py:119] From /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0920 20:21:11.972266 4504933824 deprecation_wrapper.py:119] From /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0920 20:21:11.976411 4504933824 deprecation.py:323] From /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (

Epoch 1/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4862 - acc: 0.7957
Epoch 2/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.4307 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 79us/step - loss: 0.4282 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.4231 - acc: 0.8127
Epoch 5/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.4152 - acc: 0.8282
Epoch 6/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.4096 - acc: 0.8315
Epoch 7/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.4068 - acc: 0.8334
Epoch 8/100
8000/8000 [==============================] - 1s 66us/step - loss: 0.4044 - acc: 0.8349
Epoch 9/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.4025 - acc: 0.8362
Epoch 10/100
8000/8000 [==============================] - 1s 69us/step - loss: 0.4017 - acc: 0.8340
Epoch 11

Epoch 81/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.3408 - acc: 0.8592
Epoch 82/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.3411 - acc: 0.8606
Epoch 83/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.3410 - acc: 0.8589
Epoch 84/100
8000/8000 [==============================] - 1s 73us/step - loss: 0.3413 - acc: 0.8590
Epoch 85/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3400 - acc: 0.8614
Epoch 86/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.3402 - acc: 0.8599
Epoch 87/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.3417 - acc: 0.8579
Epoch 88/100
8000/8000 [==============================] - 1s 69us/step - loss: 0.3404 - acc: 0.8609
Epoch 89/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.3406 - acc: 0.8599
Epoch 90/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.3411 - acc: 0.8615


## Part 3: Making the Predictions and Evaluating the Model

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [16]:
y_pred = (y_pred > 0.5) # Convertimos en TRUE o FALSE si se van o se quedan, al ser Classification Model.

In [17]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [18]:
cm

array([[1483,  112],
       [ 183,  222]])

In [19]:
Accuracy = (1552+196)/(2000)  #Diagonal principal es los acertados y la no principal los fallados
Accuracy

0.874

## Homework: Predict if one customer will leave the bank

In [20]:
new_prediction = classifier.predict(sc.transform(np.array([[0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

In [21]:
new_prediction = (new_prediction > 0.5)
new_prediction

array([[False]])

## Part 4: Evaluating, Improving and Tuning the ANN

In [22]:
# Evaluating the ANN (K-Fold Cross Validation)

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [23]:
# This is called wrapping

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
    classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
    classifier.add(Dense(units = 1,kernel_initializer = 'uniform',activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    return classifier


classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 100)

accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10,
                             n_jobs = -1)#n_jobs = núcleos cpu a usar


In [24]:
mean = accuracies.mean()
variance = accuracies.std()
print(mean, variance)

0.7959999969601632 0.010105690620981692


In [25]:
# Tuning the ANN

import keras
from keras.models import Sequential
from keras.layers import Dense

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [26]:
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
    classifier.add(Dense(units = 6,kernel_initializer = 'uniform',activation = 'relu'))
    classifier.add(Dense(units = 1,kernel_initializer = 'uniform',activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    return classifier


classifier = KerasClassifier(build_fn = build_classifier)

In [27]:
parameters = {'batch_size': [25,32], 
              'nb_epoch': [100,500],
             'optimizer': ['adam','rmsprop']}

grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', cv = 10)
grid_search = grid_search.fit(X_train, y_train)

best_parameters =  grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/1
7200/7200 [==============================] - 0s 61us/step - loss: 0.5534 - acc: 0.7968
Epoch 1/1
7200/7200 [==============================] - 0s 68us/step - loss: 0.5681 - acc: 0.7961
Epoch 1/1
7200/7200 [==============================] - 1s 72us/step - loss: 0.5411 - acc: 0.7956
Epoch 1/1
7200/7200 [==============================] - 1s 76us/step - loss: 0.5645 - acc: 0.7961
Epoch 1/1
7200/7200 [==============================] - 1s 82us/step - loss: 0.5469 - acc: 0.7937
Epoch 1/1
7200/7200 [==============================] - 1s 87us/step - loss: 0.5626 - acc: 0.7933
Epoch 1/1
7200/7200 [==============================] - 1s 93us/step - loss: 0.5743 - acc: 0.7951
Epoch 1/1
7200/7200 [==============================] - 1s 103us/step - loss: 0.5572 - acc: 0.7961
Epoch 1/1
7200/7200 [==============================] - 1s 108us/step - loss: 0.5667 - acc: 0.7953
Epoch 1/1
7200/7200 [==============================] - 1s 110us/step - loss: 0.5611 - acc: 0.7960
Epoch 1/1
7200/7200 [======